/* AUTO-GENERATED by scripts/collect_earnings.py — do not edit by hand.
   Beat/miss ledger + next-report consensus + estimate revisions for the
   official universe. Missing values are null, never zero. */
const EARNINGS_INTEL = {
 "asOf": null,
 "source": "Yahoo Finance quoteSummary (earningsHistory, calendarEvents, earningsTrend)",
 "tickers": {}
};
