/* AUTO-GENERATED by scripts/collect_insiders.py — SEC Form 4 insider
   transactions. Open-market PURCHASES (code P) are the signal; sales
   are mostly noise (diversification/taxes) and are never treated as a
   mirror image. Grants, option exercises and tax withholding are
   compensation mechanics, not decisions. Rule 10b5-1 trades are
   pre-scheduled and flagged out of the conviction signal.
   Seed bundle: empty but valid until the first pipeline run. */
const INSIDERS = {"asOf":null,"windowDays":90,"windowStart":null,"source":"SEC EDGAR Form 4 (ownership documents)","universe":0,"scanned":0,"partial":false,"tickers":{}};
