/* MANAGEMENT LANGUAGE — derived phrase counts from earnings-call transcripts
   (FMP) and SEC 8-K EX-99.1 earnings releases. Generated by
   scripts/collect_language.py. NO raw transcript text is stored here:
   only counts, so nothing licensed is republished and the bundle stays small.

   This is the placeholder shipped before the first collector run. The engine
   treats an empty corpus as "no reading yet" and the UI says so — it never
   invents themes from nothing. */
const LANGUAGE_META = { generated: null, companies: 0, requested: 0, sources: {}, missing: [], note: "Not yet collected — run scripts/collect_language.py." };
const LANGUAGE = {};
if (typeof window !== "undefined") { window.LANGUAGE = LANGUAGE; window.LANGUAGE_META = LANGUAGE_META; }
