/* AUTO-GENERATED by scripts/build_signals.js — the daily what-changed ledger.
   Deltas only; levels live in the score engines. Missing signals are skipped,
   never fabricated. */
const SIGNALS = {"asOf":"2026-07-24","since":"2026-07-24","events":[{"d":"2026-07-20","tk":"FDX","type":"filing","m":90,"title":"New 10-K ingested (filed 2026-07-20)","detail":"revenue growth ACCELERATED +0.3% → +7.7% YoY · diluted shares SHRANK -1.6%"},{"d":"2026-07-15","tk":"NKE","type":"filing","m":90,"title":"New 10-K ingested (filed 2026-07-15)","detail":"revenue growth ACCELERATED -9.8% → +0.2% YoY"}]};
