/* AUTO-GENERATED by scripts/build_signals.js — the daily what-changed ledger.
   Deltas only; levels live in the score engines. Missing signals are skipped,
   never fabricated. */
const SIGNALS = {"asOf":"2026-07-24","since":"2026-07-24","events":[]};
