/* AUTO-GENERATED by scripts/track_whales.py — institutional whales via
   SEC EDGAR. 13F = quarterly snapshot with a 45-day legal filing lag.
   Each whale carries a style note (active vs index vs hedged) that the
   app must display. Missing data stays missing. */
const WHALES_INTEL = {"asOf": null, "source": "SEC EDGAR", "whales": {}};
