/* AUTO-GENERATED by scripts/track_blackrock.py — BlackRock via SEC EDGAR.
   13F = quarterly snapshot with a 45-day legal filing lag; BlackRock is
   mostly an index manager, so deviations (new/exits/big trims) are the
   signal, not routine flows. Missing data stays missing. */
const BLACKROCK_INTEL = {"asOf": null, "cik": null, "name": "BlackRock Inc.", "source": "SEC EDGAR", "filings": [], "holdings": null, "f13": []};
